### ISSUE TITLE
Simpler completion UI

### ISSUE THREAD

**Issue by errordeveloper** [NeowayLabs/nashcomplete#13]
I'd like to try implementing a more minimal UI, how could I go about it?

**Comment by i4ki** [comment]
If you want to create your own autocomplete (from scratch) it's very easy: 
https://github.com/NeowayLabs/nash/blob/master/doc/interactive.md#autocomplete

In addition, there's hook functions before and after each command:
https://github.com/NeowayLabs/nash/blob/master/doc/interactive.md#hooks

Is that what you mean?
